### PR TITLE
IT-2092 Add role::puppet_master for NCSA

### PR DESCRIPTION
**Pull request by andylytical**
Add profile::puppet_master
Move common hiera from multiple sites to org/ncsa
Add Docker specific firewall exemptions to profile::docker
...Moved from baseline_cfg::firewall

### CODE REVIEW

**Comment by andylytical** [comment]
@adrienthebo @jhoblitt - FYI
These changes should not have any effect on any of your stuff.
Last I checked, you weren't using profile::docker.

**Comment by jhoblitt** [comment]
@andylytical sorry for the slow response, I thought someone had commented on this.  We are trying to get rid of profile/default.pp and have everything under a 2nd level namespace.  I can live with where it is for the time being.

**Comment by andylytical** [comment]
@jhoblitt Not sure I follow. Are you suggesting that profile::docker should be profile::ncsa::docker?

That won't be a problem, but I thought we trying to get to a point of having site/org-agnostic roles & profiles (where appropriate).

**Comment by andylytical** [comment]
I'm gonna go ahead and merge this. Adjustments can be made if needed in another branch.

**Pull request merged**
