### PR TITLE
test classes/defines using facterdb data

### PR DESCRIPTION
**Pull request by jhoblitt**
Host/role specs were converted to use facterdb in #610 .

### CODE REVIEW

**Review by cbarria — COMMENTED** [review]
only thing i see is different OS test where added (on_supported_os.each)

**Comment by jhoblitt** [comment]
@cbarria This is changing from test with an enormous set of centos 7 test of facts (copied from one of our production hosts) in `spec/default_facts.yml` to using facterdb for most test data.  facterdb contains dumps of facts from all of the operatingsystems we are likely to use and saves us the effort of having to copy in test facts for EL7, EL8, etc.

**Comment by cbarria** [comment]
great! thanks for the explanation, didn't knew what facterdb does, now i know why so much declarative code when away! 👍

**Comment by jhoblitt** [comment]
`facterdb` is a ruby gem which was already present as a dep of `voxpupuli-test`.  https://github.com/voxpupuli/facterdb

**Review by cbarria — APPROVED** [review]
thanks for the explanation on facterdb 👍

**Pull request merged**
