### PR TITLE
initial comcam-arctl role

### PR DESCRIPTION
**Pull request by jhoblitt**
The initial comcam-arctl role:
* installs rabbitmq 3.8.3 + manage queue creation
* installs redis 5.0.5 from scl + enables the scl by default
* installs redis package from pypi
* installs docker + docker-compose
* nfs exports `/data/lsstdata`
* manages the `arc` user + `archive` group
* manages the `atadbot` user/group
* installs a sudo rule to allow members of the `comcam-archive-sudo` user group to `sudo` to role accounts without a passphrase

### CODE REVIEW

**Comment by jhoblitt** [comment]
This isn't yet ready for review -- this is currently an FYI

**Comment by jhoblitt** [comment]
Requires https://github.com/lsst-it/lsst-puppet-hiera-private/pull/22

**Comment by jhoblitt** [comment]
This PR is ready for review

**Comment by jhoblitt** [comment]
rebased on current master.

@andylytical I'm happy to have the conversation but my basic position is that a profile that does nothing but include a 3rd party mod doesn't provide much value.

**Comment by andylytical** [comment]
@jhoblitt (regarding "essentially empty profiles") I agree and we've run into similar. I may have interpreted the Puppet recommendations too literally. I like the way you've set this one up and look forward to further discussions and ideas. I'll add it to (some future) devops coordination meeting.

**Comment by jhoblitt** [comment]
It has been two hours and travis hasn't run.  I'm going to force the merge without waiting any longer...

**Pull request merged**
