### PR TITLE
Pull request to merge changes for xml 14

### PR DESCRIPTION
**Pull request by mxturri**
Pull request to merge changes for xml 14

### CODE REVIEW

**Review by jhoblitt — CHANGES_REQUESTED** [review]
I see a couple of issues:
- It needs to be rebased on current `master`.
- Similar to #678, it needs a more descriptive PR title.
- The puppet-lint errors need to be resolved.

**Comment by mxturri** [comment]
Can the rebase be done via the web interface?
I don't know what the puppet-lint errors are and/or how to fix them

**Comment by jhoblitt** [comment]
@mxturri It isn't giving me the option to rebase from the www interface, I don't know why. It is just `git rebase origin/master` from the cli.

The puppet-lint errors are reported in the gha workflow output: https://github.com/lsst-it/lsst-itconf/actions/runs/4086773536/jobs/7046475030

**Comment by mxturri** [comment]
I did what you asked. On this branch I issued a 
git rebase origin/master
There were some more conflicts that I resolved.
I am now stuck here:

`
turri@PC95349:~/Code/LSST/puppet/lsst-itconf$ git status
rebase in progress; onto 440299ba
You are currently rebasing branch 'IT-4165_ComCam_AuxTel_XML14' on '440299ba'.
  (all conflicts fixed: run "git rebase --continue")

nothing to commit, working tree clean
turri@PC95349:~/Code/LSST/puppet/lsst-itconf$ git rebase --continue
Applying: Update comcam-ccs.yaml
No changes - did you forget to use 'git add'?
If there is nothing left to stage, chances are that something else
already introduced the same changes; you might want to skip this patch.

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
`

**Comment by mxturri** [comment]
Is there a way to make this process more transparent and possibly easier?

**Comment by jhoblitt** [comment]
@mxturri It took me only a couple of minutes to rebase your branch manually resolving the errors.  This can also be done mostly automatically by setting the merge strategy. See the `git-rebase(1)` man page.  

The output of the git command gives pretty good instructions as to what needs to be done.  The multiple merge commits from the master branch and different points in time are why the rebase is encouring merge errors. If you use rebase instead of merge, that won't happen.

The closed/merge PRs in this repo are good examples of [mostly] acceptable PR titles: https://github.com/lsst-it/lsst-itconf/pulls?q=is%3Apr+is%3Aclosed

**Comment by jhoblitt** [comment]
It appears that github has a useful page on rebasing: https://docs.github.com/en/get-started/using-git/about-git-rebase

**Comment by mxturri** [comment]
@jhoblitt I am glad this process was easy for you. On the other hand it is still not clear to me why it failed for me following the instructions you provided.
I hope the updated title will be to your liking.

**Review by jhoblitt — CHANGES_REQUESTED** [review]
This PR still needs to be rebased on the current master to remove the multiple merge commits.

**Comment by mxturri** [comment]
@jhoblitt it's not clear to me what the difference is between your latest request
`This PR still needs to be rebased on the current master to remove the multiple merge commits.`
and your original request
`It needs to be rebased on current master.`
Either way rebasing to master is still not working for me.
Please go ahead and make the needed changes.

**Comment by jhoblitt** [comment]
@mxturri There are numerous resources online to help learn basic git functionality including how to rebase. Rebasing PRs is the standard workflow within LSST DM. See: https://developer.lsst.io/work/flow.html  If you are still struggling with using git, I can try to schedule a video conference with you on Wednesday or Thursday of next week to walk you through a rebase.

I do not think that starting a PR title with "Pull request" is any more reasonable than prefixing commit titles with "commit".  Here are some examples of your previous PRs with descriptive titles:

- https://github.com/lsst-camera-ccs/org-lsst-ccs-drivers-daq/pull/13
- https://github.com/lsst-camera-ccs/org-lsst-ccs-subsystem-image-handling/pull/16
- https://github.com/lsst-camera-ccs/org-lsst-ccs-subsystem-mmm/pull/2

Note that the DM and industry standard is for commit messages (and PR titles) to be in imperative tense: https://developer.lsst.io/work/flow.html#appendix-commit-message-best-practices

**Comment by jhoblitt** [comment]
@mxturri The request is still the same. You click the re-request review button without performing the requested action.

**Comment by mxturri** [comment]
To install the needed software we don't need to merge this branch onto master.

**Pull request closed without merging**
