### PR TITLE
Comcam mcm sal

### PR DESCRIPTION
**Pull request by glennmorris**
This will enable management of CCS SAL on comcam-mcm, as per https://jira.lsstcorp.org/browse/IT-2613

### CODE REVIEW

**Review by hreinking — APPROVED** [review]
LGTM, but, we will have the same conflict when rebasing @tony-johnson's branch.

**Comment by tony-johnson** [comment]
One small comment, I also added:

> /etc/systemd/system/ocs-bridge-comcam-dev.service
> /etc/systemd/system/mcm-comcam-dev.service

both of which point to /lsst/ccs/dev rather than prod, and also in the case of the first one have an extra env var set. It would be good to get these included into the puppet setupm but it might need some discussion,

We will need to merge this into the IT2753 branch to deploy it on comcam.

**Comment by jhoblitt** [comment]
I have no objection to this but it would be great if we could eventually merge this module with https://github.com/lsst-it/puppet-sal2 so we do not have to support two modules that do essentially the same thing.

**Comment by glennmorris** [comment]
Although I believe it would be fine to merge this as-is, it may make sense to wait and include
https://github.com/lsst-it/puppet-ccs_sal/pull/4

**Pull request merged**
